jwt:
  secret: "404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970"
user:
  service:
    url: http://localhost:8081
spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://localhost:3306/notes_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 1057555034
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          jws-algorithms: HS512
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: notes-event-consumer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
logging:
  level:
    org.springframework.security: DEBUG
    com.example.note_service.client: DEBUG
    feign: DEBUG
    feign.Logger: DEBUG
    feign.codec: DEBUG
    feign.okhttp: DEBUG
    org.springframework.cloud.openfeign: DEBUG
    org.springframework.web.client: DEBUG

resilience4j:
  circuitbreaker:
    instances:
      userService:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        failureRateThreshold: 50
        waitDurationInOpenState: 30s
  retry:
    instances:
      userService:
        maxAttempts: 5
        waitDuration: 1s
        retryExceptions:
          - feign.RetryableException
          - org.springframework.web.client.HttpServerErrorException
